### PR TITLE
feature/cdp-deploy-and-all-maintainer-instructions

### LINKED ISSUE #31: Create Github Action Bot 2 for CDP Instance Creation
## Use Case
Step 3 of the automated process to optimize the CDP instance creation

## Solution
Github action bot that creates the repo

- Triggered by comment we add when we see 
           - bot 1 success message and 
           - user comment choosing to proceed
- Adds files to hosting repo
- Adds maintainer as collaborator to CDP repo
- Adds success comment when completed with hosting URL

### PR DESCRIPTION
**Pull request by JacksonMaxfield**
### Link to Relevant Issue

This pull request resolves #31 

### Description of Changes

_Include a description of the proposed changes._

Adds the "/cdp-deploy" command to the repo and updates commands to document the process of deployment for CDP maintainers. Currently I am the only person who has access to the Google Cloud and Pulumi account passwords but that can easily change in the future to allow more people the ability to do this :slightly_smiling_face: 

The new workflow (and maintainer documentation / steps) can be seen in this screenshot: 
image

From: https://github.com/JacksonMaxfield/cookiecutter-cdp-deployment/issues/68

The process isn't fully automated unfortunately because Google Service Accounts (used for autonomous resource creation and management) only have access to the project they were created under unless they were specifically created to be an "Organization Service Account" -- CDP doesn't have a GCP organization and after looking into it, looks a bit complicated to setup. So for now, we have some manual steps, however the whole process of deploying an instance, even with these manual steps takes about ~10 minutes (given that the scraper has already been added to `cdp-scrapers`).

Video of the full deployment process can be found in Slack.

### CODE REVIEW

**Comment by JacksonMaxfield** [comment]
Also tagging @dphoria

**Comment by sarahjliu** [comment]
this is amazing, jackson! so exciting to see all these steps being automated 😁

A few questions I had about the process:
- In your video, you mentioned that the event gather pipeline can't be manually triggered the first time so how will it get triggered the first time? will that be done as a part of bot 2?
- You also mentioned that we can set the start date and end date for event gathering, does this mean that when the bot 2 work + manual work is completed and we have an new instance website, the website won't contain any data in the beginning? If so, I'm thinking we can have a predetermined event start date + end date so the website we give can be populated with data and the users can work with us if they want a different start date or end date
- - thoughts on moving all the CDP Maintainer information to a separate internal document so we can conceal all that from the external user and clean up the issue comments?

Here are some language specific asks that aren't required for the completion of this pr and I can create a separate issue with but adding it here for convenience:
- adding "..." at the end of the bot 1 form validation steps when it is still validating the info
- "generated" → "generated key" in bot 2 Final Steps checkbox 2
- adding a line to the bot 2 comment saying it'll take an additional 10 min to complete the set-up and we will comment with the instance website link when it is complete
- bot 2 comment "Deployment Status - Completed" -> "Deployment Status - In Progress"
- adding a step in Final Steps saying to manually add a comment with "Deployment Status - Completed" and the instance link when it is fully set up
- "CDP Maintainers" → "Steps for Internal CDP Team"

**Comment by JacksonMaxfield** [comment]
>     * In your video, you mentioned that the event gather pipeline can't be manually triggered the first time so how will it get triggered the first time? will that be done as a part of bot 2?

It runs on a schedule! The pipeline will automatically run every 6 hours so no need for us to do anything, it will "just work". But I actually may change this to just have the job run and do nothing on every push to main so that it is instantly available for manual backfill.

>     * You also mentioned that we can set the start date and end date for event gathering, does this mean that when the bot 2 work + manual work is completed and we have an new instance website, the website won't contain any data in the beginning? If so, I'm thinking we can have a predetermined event start date + end date so the website we give can be populated with data and the users can work with us if they want a different start date or end date

See my answer above, but yes this is correct. The database (and thus the website) will have no event data in it on inital push / repo create. With the current setup it will only have data when it his one of the 0, 6, 12, or 18 hour marks for automatic event processing (or if manually triggered). Having it run everytime a commit is pushed to main is dangerous because the infrastructure could be out-of-sync with the pipeline (i.e. infra not setup and pipeline attempting to run and store data results in pipeline failure, granted its a safe failure but could be confusing).

I think the solution is to have the job just trigger on push but not actually do anything on push so that it is instantly available for manual backfill and then all the other automated stuff runs on their normal 6 hour jobs.

>     * thoughts on moving all the CDP Maintainer information to a separate internal document so we can conceal all that from the external user and clean up the issue comments?

I actually particularly like having the checklist available for me + I thought it provided a method to the user to monitor _our_ progress as to instance deployment.

**Comment by isaacna** [comment]
I think this is great and the automated bot really simplifies and speeds things up! 

Nitpick, but should we mention somewhere in the workflow to run all the infrastructure commands in `cdp-backend/dev-infrastructure` directory? Or link them to the [README](https://github.com/CouncilDataProject/cdp-backend/tree/main/dev-infrastructure) with more specific details on that?

**Comment by sarahjliu** [comment]
these are basic ques but I'm just trying to wrap my head around this 😅 
1. If we make the job run on push but not do anything, it seems like we would still need to wait until hour 0, 6, 12, or 18 for the first data batch to get added so what is the benefit on having it run on push? (aka what does "instantly available for manual backfill" mean?)
2. how much data is contained in the first data batch?

It would be good to add this info in the final comment so the external user has the correct expectations about the website data. I can add that in my separate issue 👍

**Comment by JacksonMaxfield** [comment]
> Nitpick, but should we mention somewhere in the workflow to run all the infrastructure commands in `cdp-backend/dev-infrastructure` directory? Or link them to the [README](https://github.com/CouncilDataProject/cdp-backend/tree/main/dev-infrastructure) with more specific details on that?

Agree. Will add to the comment.

> 1. If we make the job run on push but not do anything, it seems like we would still need to wait until hour 0, 6, 12, or 18 for the first data batch to get added so what is the benefit on having it run on push? (aka what does "instantly available for manual backfill" mean?)

Correct. If we make the job run on push but not do anything the next _actual_ data ingestion would run at one of the six hour marks. The benefit of making it do a fake run on push is simply to have the workflow available for manual usage through the github UI. I need to test how it all works but I think it will be better.

> 2. how much data is contained in the first data batch?

By default, most of the legistar / scrapers we have written currently check the last two days worth of data. Any of the automated systems / pipelines by that default will mean that they will collect and process the last two days. The manual pipeline can be triggered with parameters for `from` and `to` i.e. you can manually backfill any range of data (granted that the processing time for the range is less than 6 hours because that is how long github actions jobs allow you to run for)

**Review by sarahjliu — APPROVED** [review]
Thanks for the info! The overall logic looks good to me and I’ll add the language nitpicks separately

**Review by isaacna — APPROVED** [review]

**Comment by JacksonMaxfield** [comment]
@sarahjliu I fixed _some_ of the text / language stuff you noted but everything else looks good to go will be excited to show off updates at tonight's meeting.

**Pull request merged**
