### PR TITLE
feature/add-server-region-option

### LINKED ISSUE #16: Add option to choose infrastructure server locations
## Use Case
*Please provide a use case to help us understand your request in context*

Currently the `CDPStack` object in the infra directory defaults to using `us-west2` for all infrastructure creation but it would be nice if we added a cookiecutter option with a list of server locations or user enters their own.

## Solution
*Please describe your ideal solution*

Add a cookiecutter list option for: `infrastructure_location` with options such as:
```
[
    "us-west1",
    "us-west2",
    "us-east1",
]
```

etc.

Will need to pass the chosen option down to the `CDPStack` object.
[List of Firestore supported regions](https://firebase.google.com/docs/firestore/locations)

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

### PR DESCRIPTION
**Pull request by isaacna**
**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [x] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
 - Resolves #16 
- [x] Provide context of changes.
 - Adding firestore region option to cookiecutter template
- [x] Provide relevant tests for your feature or bug fix.
 - Created a repo after these changes and confirmed that `CDPStack` has the `firestore_region` set
- [x] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

### CODE REVIEW

**Review by JacksonMaxfield — COMMENTED** [review]
Can you also add the selected region to the [cookiecutter.yml file](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/blob/main/%7B%7B%20cookiecutter.hosting_github_repo_name%20%7D%7D/cookiecutter.yaml)

For context, that YAML file is used in the `make upgrade-from-cookiecutter` command as a way of storing prior configuration.

**Review by hawkticehurst — APPROVED** [review]
LGTM!

**Comment by isaacna** [comment]
> Can you also add the selected region to the [cookiecutter.yml file](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/blob/main/%7B%7B%20cookiecutter.hosting_github_repo_name%20%7D%7D/cookiecutter.yaml)
> 
> For context, that YAML file is used in the `make upgrade-from-cookiecutter` command as a way of storing prior configuration.

Good catch, done

**Comment by JacksonMaxfield** [comment]
Looks like after other PRs there are some merge conflicts. Merge main then merge whenever 👍

**Pull request merged**
