### PR TITLE
feature/form-validation-bot-basics

### PR DESCRIPTION
**Pull request by JacksonMaxfield**
### Link to Relevant Issue

Work in progress on #30 

### Description of Changes

_Include a description of the proposed changes._

Adds the basic struction of how I will be moving forward with bot 1.
I tried to do it with all GitHub Action steps and the like but it was just easier to do everything in Python. Here is a recorded demo:

https://user-images.githubusercontent.com/17132317/129470394-f657f49e-c854-4d84-8ac2-9f4e8153ba72.mp4

And you can also give it a try by making an issue on my fork: [JacksonMaxfield/cookiecutter-cdp-deployment/issues](https://github.com/JacksonMaxfield/cookiecutter-cdp-deployment/issues)

Tagging more than just @hawkticehurst and @sarahjliu because this is neato and some people may not be in the loop as to how the deployment bots are planned / will work. (tagging @dphoria here because I can't ask for your review for some reason...)

---

If possible it would be great to merge this PR and then I will work on the rest of bot 1 just looking for initial feedback for now.

Things still left to add:
1. more fields to the form, I think we should more of the cookiecutter content, and dry run the cookiecutter creation process.
2. checking minimum data from legistar

### CODE REVIEW

**Comment by tohuynh** [comment]
Looks cool.

Would it be possible to add the field validation error message in the original issue (underneath the field) at all?

You can results of the instance creation in another moment though.

**Comment by JacksonMaxfield** [comment]
> Looks cool.
> 
> Would it be possible to add the field validation error message in the original issue (underneath the field) at all?
> 
> You can put the results of the instance creation in another comment though.

Possible but a bit more difficult. I personally like having the initial comment of form validation posted because we can add things to it like "One of us on the team will respond as soon as we are available to run a more thorough test of the planned deployment." or something.

**Comment by tohuynh** [comment]
I see. Do you expect the gh-issue creator to edit the gh-issue in case of errors, or will it be us?

We might need to add some documentation about what to do for each case after gh-issue creation?

**Comment by JacksonMaxfield** [comment]
> Do you expect the gh-issue creator to edit the gh-issue in case of errors

I do.

> We might need to add some documentation...

Totally agree, it's been partially laid out in the project spec but I other deployment systems like this that I have seen usually add a comment specifically for the admin when all checks are successful that reads something like:

"@JacksonMaxfield, all checks are successful. To deploy this instance respond in this issue thread with `/cdp-deploy`

**Review by sarahjliu — APPROVED** [review]
wow this is great, so exciting to see it in action!

NIT: can we add a line to the github bot comment like "I will automatically rerun the checks after you update the issue to validate the changes" so it's clear to the user?

**Comment by JacksonMaxfield** [comment]
> wow this is great, so exciting to see it in action!
> 
> NIT: can we add a line to the github bot comment like "I will automatically rerun the checks after you update the issue to validate the changes" so it's clear to the user?

Absolutely.

**Comment by JacksonMaxfield** [comment]
@sarahjliu Because I personally care about it, I added the dry run of the cookiecutter and logged the cookiecutter params:

image

Up next is Legistar attempts. Will do that when I get back tonight.

**Pull request merged**
